class CardDatabase {
    static getAllCards() {
        return [
            { name: 'Geezard', ranks: [1, 4, 1, 5] },
            { name: 'Funguar', ranks: [5, 1, 3, 1] },
            { name: 'Bite Bug', ranks: [1, 3, 3, 5] },
            { name: 'Red Bat', ranks: [6, 1, 2, 6] },
            { name: 'Blobra', ranks: [2, 3, 1, 5] },
            { name: 'Gayla', ranks: [2, 1, 4, 4] },
            { name: 'Gesper', ranks: [1, 1, 5, 4] },
            { name: 'Fastitocalon-F', ranks: [3, 5, 2, 1] },
            { name: 'Blood Soul', ranks: [2, 1, 6, 1] },
            { name: 'Caterchipillar', ranks: [4, 2, 4, 3] },
            { name: 'Cockatrice', ranks: [2, 1, 2, 6] },
            { name: 'Grat', ranks: [7, 1, 3, 1] },
            { name: 'Buel', ranks: [6, 2, 2, 3] },
            { name: 'Mesmerize', ranks: [5, 3, 3, 3] },
            { name: 'Glacial Eye', ranks: [6, 1, 4, 3] },
            { name: 'Belhelmel', ranks: [3, 4, 5, 3] },
            { name: 'Thrustaevis', ranks: [5, 3, 2, 5] },
            { name: 'Anacondaur', ranks: [5, 1, 3, 5] },
            { name: 'Creeps', ranks: [5, 2, 5, 2] },
            { name: 'Grendel', ranks: [4, 4, 5, 2] },
            { name: 'Jelleye', ranks: [3, 2, 1, 7] },
            { name: 'Grand Mantis', ranks: [5, 2, 5, 3] },
            { name: 'Forbidden', ranks: [6, 6, 3, 2] },
            { name: 'Armadodo', ranks: [6, 3, 1, 6] },
            { name: 'Tri-Face', ranks: [3, 5, 5, 5] },
            { name: 'Fastitocalon', ranks: [7, 5, 1, 3] },
            { name: 'Snow Lion', ranks: [7, 1, 5, 3] },
            { name: 'Ochu', ranks: [5, 6, 3, 3] },
            { name: 'SAM08G', ranks: [5, 6, 4, 2] },
            { name: 'Death Claw', ranks: [4, 4, 7, 2] },
            { name: 'Cactuar', ranks: [6, 2, 6, 3] },
            { name: 'Tonberry', ranks: [3, 6, 4, 4] },
            { name: 'Abyss Worm', ranks: [7, 2, 3, 5] },
            { name: 'Turtapod', ranks: [2, 3, 6, 6] },
            { name: 'Vysage', ranks: [6, 5, 4, 2] },
            { name: 'T-Rexaur', ranks: [4, 6, 2, 7] },
            { name: 'Bomb', ranks: [2, 7, 6, 1] },
            { name: 'Blitz', ranks: [1, 6, 4, 5] },
            { name: 'Wendigo', ranks: [7, 3, 1, 6] },
            { name: 'Torama', ranks: [7, 4, 4, 2] },
            { name: 'Imp', ranks: [3, 7, 3, 3] },
            { name: 'Blue Dragon', ranks: [6, 2, 7, 3] },
            { name: 'Adamantoise', ranks: [4, 5, 5, 6] },
            { name: 'Hexadragon', ranks: [7, 5, 3, 4] },
            { name: 'Iron Giant', ranks: [6, 5, 5, 5] },
            { name: 'Behemoth', ranks: [3, 6, 5, 7] },
            { name: 'Chimera', ranks: [7, 6, 5, 1] },
            { name: 'PuPu', ranks: [3, 1, 2, 'A'] },
            { name: 'Elastoid', ranks: [6, 2, 6, 7] },
            { name: 'GIM47N', ranks: [5, 5, 3, 7] },
            { name: 'Malboro', ranks: [7, 7, 4, 2] },
            { name: 'Ruby Dragon', ranks: [7, 2, 7, 4] },
            { name: 'Elnoyle', ranks: [5, 3, 7, 6] },
            { name: 'Tonberry King', ranks: [4, 6, 7, 4] },
            { name: 'Biggs, Wedge', ranks: [6, 6, 2, 7] },
            { name: 'Fujin, Raijin', ranks: [2, 8, 8, 4] },
            { name: 'Elvoret', ranks: [7, 8, 3, 4] },
            { name: 'X-ATM092', ranks: [4, 3, 8, 7] },
            { name: 'Granaldo', ranks: [7, 2, 8, 5] },
            { name: 'Gerogero', ranks: [1, 3, 8, 8] },
            { name: 'Iguion', ranks: [8, 2, 8, 2] },
            { name: 'Abadon', ranks: [6, 8, 4, 5] },
            { name: 'Trauma', ranks: [4, 8, 5, 6] },
            { name: 'Oilboyle', ranks: [1, 8, 4, 8] },
            { name: 'Shumi Tribe', ranks: [6, 5, 4, 8] },
            { name: 'Krysta', ranks: [7, 1, 5, 8] },
            { name: 'Propagator', ranks: [8, 4, 4, 8] },
            { name: 'Jumbo Cactuar', ranks: [8, 8, 6, 2] },
            { name: 'Tri-Point', ranks: [8, 5, 2, 8] },
            { name: 'Gargantua', ranks: [4, 7, 8, 6] },
            { name: 'Mobile Type 8', ranks: [8, 6, 7, 3] },
            { name: 'Sphinxara', ranks: [8, 3, 5, 8] },
            { name: 'Tiamat', ranks: [8, 8, 4, 6] },
            { name: 'BGH251F2', ranks: [5, 7, 8, 7] },
            { name: 'Red Giant', ranks: [6, 7, 8, 4] },
            { name: 'Catoblepas', ranks: [1, 8, 7, 8] },
            { name: 'Ultima Weapon', ranks: [7, 7, 2, 8] },
            { name: 'Chubby Chocobo', ranks: [4, 4, 8, 9] },
            { name: 'Angelo', ranks: [9, 6, 7, 3] },
            { name: 'Gilgamesh', ranks: [3, 7, 9, 6] },
            { name: 'MiniMog', ranks: [9, 3, 2, 6] },
            { name: 'Chicobo', ranks: [9, 4, 8, 2] },
            { name: 'Quezacotl', ranks: [2, 9, 9, 4] },
            { name: 'Shiva', ranks: [6, 7, 4, 9] },
            { name: 'Ifrit', ranks: [9, 6, 2, 8] },
            { name: 'Siren', ranks: [8, 2, 9, 6] },
            { name: 'Sacred', ranks: [5, 1, 9, 9] },
            { name: 'Minotaur', ranks: [9, 5, 2, 9] },
            { name: 'Carbuncle', ranks: [8, 4, 4, 'A'] },
            { name: 'Diablos', ranks: [5, 'A', 8, 3] },
            { name: 'Leviathan', ranks: [7, 'A', 1, 7] },
            { name: 'Odin', ranks: [8, 'A', 2, 8] },
            { name: 'Pandemona', ranks: ['A', 7, 1, 7] },
            { name: 'Cerberus', ranks: [7, 4, 6, 'A'] },
            { name: 'Alexander', ranks: [9, 'A', 4, 2] },
            { name: 'Phoenix', ranks: [7, 2, 7, 'A'] },
            { name: 'Bahamut', ranks: ['A', 8, 2, 6] },
            { name: 'Doomtrain', ranks: [3, 1, 'A', 'A'] },
            { name: 'Eden', ranks: [4, 4, 9, 'A'] },
            { name: 'Ward', ranks: ['A', 7, 2, 8] },
            { name: 'Kiros', ranks: [6, 7, 6, 'A'] },
            { name: 'Laguna', ranks: [5, 9, 3, 'A'] },
            { name: 'Selphie', ranks: ['A', 8, 6, 4] },
            { name: 'Quistis', ranks: [9, 6, 'A', 2] },
            { name: 'Irvine', ranks: [2, 'A', 9, 6] },
            { name: 'Zell', ranks: [8, 5, 'A', 6] },
            { name: 'Rinoa', ranks: [4, 'A', 2, 'A'] },
            { name: 'Edea', ranks: ['A', 3, 'A', 3] },
            { name: 'Seifer', ranks: [6, 9, 6, 'A'] },
            { name: 'Squall', ranks: ['A', 4, 6, 9] }
        ];
    }

    static getRandomCards(count) {
        const allCards = this.getAllCards();
        const shuffled = [...allCards].sort(() => Math.random() - 0.5);
        return shuffled.slice(0, count);
    }

    static getPlayerCollection() {
        const allCards = this.getAllCards();
        const shuffled = [...allCards].sort(() => Math.random() - 0.5);
        return shuffled.slice(0, 20);
    }
}

module.exports = CardDatabase;